spring:
  profiles:
    active: dev
  druid:
    druidClassName: oracle.jdbc.driver.OracleDriver
    #最大连接数
    maxActive: 30
    #最小连接数
    minIdle: 5
    #获取连接的最大等待时间
    maxWait: 10000
    #解决mysql8小时的问题
    validationgQuery: SELECT 'X'
    #空闲连接的检查时间间隔
    timeBetweenEvictionRunsMillis: 60000
    #空闲连接最小空闲时间
    minEvictableIdleTimeMillis: 300000
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
pagehelper:
  supportMethodsArguments: true
  reasonable: true
  helperDialect: oracle
  params: count=countSql
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8088
  #编码格式
  tomcat:
    uri-encoding: UTF-8
