app:
  db:
    host: 192.168.50.110
    port: 1521
    dbname: orcl
    username: engadmin
    password: 123456
  redis:
#    host: 192.168.50.181
    host: 10.16.21.66
    port: 6379
  rabbitmq:
    addresses: 192.168.50.181:5672
    username: guest
    password: guest
#  defaultZone: http://crux-cloud-discovery:31209/eureka/
  defaultZone: https://dev81.yonyougov.top/eureka
spring:
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@${app.db.host}:${app.db.port}:${app.db.dbname}
    username: ${app.db.username}
    password: ${app.db.password}
  rabbitmq:
    addresses: ${app.rabbitmq.addresses}
    username: ${app.rabbitmq.username}
    password: ${app.rabbitmq.password}
    publisher-confirms: true
    listener:
      simple:
        acknowledge-mode: manual
    template:
      mandatory: true
  redis:
    host: ${app.redis.host}
    port: ${app.redis.port}
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: ptp-engine
pagehelper:
  supportMethodsArguments: true
  reasonable: true
  helperDialect: oracle
  params: count=countSql
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8082
  servlet:
    context-path: /ptp-engine

eureka:
  client:
    enabled: true
    registerWithEureka: false
    serviceUrl:
      #      defaultZone: http://10.16.21.43:8761/eureka/
      defaultZone: ${app.defaultZone}
