spring:
  druid:
    url: jdbc:oracle:thin:@192.168.50.110:1521:orcl
    username: engadmin
    password: 123456
  jpa:
    database: ORACLE
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.Oracle10gDialect
      ddl-auto: update
com:
  ufgov:
    config:
      enableSwagger: true
logging:
  level:
    com:
      yonyougov:
        eng:
          mapper: debug
