app:
  db:
    host: 192.168.50.110
    port: 1521
    dbname: orcl
    username: engadmin
    password: 123456
  rabbitmq:
    host: 10.10.65.43:5672
  redis:
    host: 10.16.21.66
    port: 6379
  eureka:
    defaultZone: https://dev81.yonyougov.top/eureka
    registerWithEureka: false
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@${app.db.host}:${app.db.port}:${app.db.dbname}
    username: ${app.db.username}
    password: ${app.db.password}
  rabbitmq:
    addresses: ${app.rabbitmq.host}
    username: ${app.rabbitmq.username}
    password: ${app.rabbitmq.password}
    publisher-confirms: true
    listener:
      simple:
        acknowledge-mode: manual
    template:
      mandatory: true
  redis:
    host: ${app.redis.host}
    port: ${app.redis.port}
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: ptp-engine
pagehelper:
  supportMethodsArguments: true
  reasonable: true
  helperDialect: oracle
  params: count=countSql
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080
  servlet:
    context-path: /ptp-engine

eureka:
  client:
    enabled: true
    registerWithEureka: ${app.eureka.registerWithEureka}
    serviceUrl:
      #      defaultZone: http://10.16.21.43:8761/eureka/
      defaultZone: ${app.eureka.defaultZone}
